# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f23b362cbcf2b88cc46f59be683b061c3c3b436579e9c46f61520fb6bc1034587befca270fd819468417de231bfc62ead2300afc05eb4c0e627c636c24d8fd4

test:
  secret_key_base: 811c87dd148dfb0c303d22d37955d38bd48439e3ddaea975cc4d651bea67fcaa5b71eb0364cbabe8c523d746da19711c11ec17d8883d5eafc8b0fc263f4ab697

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
